repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^apps/data-profiling-node/
      - id: ruff-format
        files: ^apps/data-profiling-node/

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
      - id: pyright
        files: ^apps/data-profiling-node/
        args: ["--project=apps/data-profiling-node"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy-data-profiling-node
        files: ^apps/data-profiling-node/
        args: ["--config-file=apps/data-profiling-node/mypy.ini", "--show-error-codes"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        files: ^apps/data-profiling-node/