name: admin_be CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/admin-be/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: install requirements
        run: |
          cd apps/admin-be
          npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.user_name }}
          password: ${{ secrets.password }}

      - name: Build Docker image
        run: |
          cd apps/admin-be
          docker build -t tinsu2/admin-api-gateway:latest .

      - name: Push Docker image
        run: |
          docker push tinsu2/admin-api-gateway:latest
