name: feature_engineering_node CI

on:
  push:
    paths:
      - "apps/feature-engineering-node/**"
  pull_request:
    branches:
      - main
    path:
      - "apps/feature-engineering-node/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: install requirements
        run: |
          cd apps/feature-engineering-node
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd apps/feature-engineering-node
          python -m unittest tests/dummy_test.py
