name: classical_modeling_node CI

on:
  push:
    paths:
      - "apps/classical-modeling-node/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: install requirements
        run: |
          cd apps/classical-modeling-node
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd apps/classical-modeling-node
          python -m unittest tests/dummy_test.py
